zc - add custom toLocalISO convert function
ucsb-cs156-s24/proj-happycows-s24-4pm-7 pull request #13
Opened 2024-05-18 11:10 UTC by chendashi

## Overview

In this PR, I fixed the starting date bug by adding a custom conversion function. The current toISOString() convert the local time to UTC, and my custom function convert it into ISO format with correct date, time, and timezone, so that no matter where the user are, the corrected starting date will always be displayed.

## Screenshots (will add another screenshot when local time is one day differ from the UTC time)
![WeChat520a11b9a45a0e6b80eb766d34b5e0b1](https://github.com/ucsb-cs156-s24/proj-happycows-s24-4pm-7/assets/17016528/c845f66a-121a-422f-a3c9-c756059c254c)

## Feedback Request
- This function is only implemented in CommonsForm.js, will any other components need changes?

## Future Possibilities
- avoid user manipulate local time (i.e. set date backwards)(?)

## Validation
a debug version was deployed at
'''https://happycows-chendashi-dev.dokku-07.cs.ucsb.edu'''
try go there on 6:00pm if you timezone is PDT

## Tests
- not needed for this bug

## Linked Issues
Closes #2

2024-05-19 23:09 UTC, YixinXue submitted a review, later dismissed
LGTM

2024-05-20 19:53 UTC, pconrad requested changes
This is a good start.  But why stop there?  There is more refactoring to be done here.

2024-05-22 05:18 UTC, YixinXue approved these changes
Excellent job!

2024-05-23 05:21 UTC, pconrad approved these changes
LGTM!  Nicely done

2024-05-23 05:21 UTC, merged