mz - adding "edit commons" button to users table for admins
ucsb-cs156-s24/proj-happycows-s24-4pm-7 pull request #15
Opened 2024-05-18 21:37 UTC by mczimmermann

## Overview
In this PR, I added an "Edit Commons" button column on the users table for admins to be able to remove certain users from certain commons if they are causing issues. Currently, the button serves as a placeholder and clicking it does not actually redirect/do anything.

## Screenshots
<img width="860" alt="Screen Shot 2024-05-18 at 2 36 53 PM" src="https://github.com/ucsb-cs156-s24/proj-happycows-s24-4pm-7/assets/86985941/439346b8-c7d7-4832-a15b-8a5a988a3415">

## Feedback Request 
Please give suggestions on the following:
- Should users that are admins not have "Edit Commons" buttons next to them? Would it ever be necessary to remove an admin from a commons?
- I'm not sure if this is the most intuitive design, I'm open to other ideas about how it could be implemented better. 

## Future Possibilities 
Some possible points could be:
- This is the beginning/part of the "edit commons", and we will need to implement the actual remove page for it to work.

## Validation (Optional)
1. Download this branch.
2. Run the project.
3. Go to "Users" under "Admin".
4. Check that for all users you can see a button that says "Edit Commons".

## Tests
- [ ] Backend Unit tests (`mvn test`) pass
- [ ] Backend Test coverage (`mvn test jacoco:report`) 100%
- [ ] Backend Mutation tests (`mvn test pitest:mutationCoverage`) 100% 
- [ ] Frontend Unit tests (`npm test`) pass
- [ ] Frontend Test coverage (`npm run coverage`) 100%
- [ ] Frontend Mutation tests (`npx stryker run`) 100% 
- [ ] Frontend Linting (`npx eslint --fix src`) 

## Linked Issues
Related to #8, does not close it.

2024-05-20 19:59 UTC, pconrad requested changes
> Currently, the button serves as a placeholder and clicking it does not actually redirect/do anything.

Typically, we try to not merge code into main that is broken.  It is true that we like to break PRs into small pieces, but in this case, it's "too small a piece".  Please at least link to a placeholder page for the edit page that says something like "Edit not implemented yet; coming soon".

Also see other comments in the review about "commented out code"

2024-05-20 19:59 UTC, pconrad commented on frontend/src/main/components/Users/UsersTable.js
> +    // }
https://ucsb-cs156.github.io/topics/code_reviews/commented_out_code.htm

2024-05-20 19:59 UTC, pconrad commented on frontend/src/main/components/Users/UsersTable.js
> +    const removeCallback = (_cell) => { }
Why do we have a callback that does nothing?

2024-05-22 05:54 UTC, mczimmermann commented
<img width="850" alt="Screen Shot 2024-05-21 at 10 53 11 PM" src="https://github.com/ucsb-cs156-s24/proj-happycows-s24-4pm-7/assets/86985941/9ac06d7b-c94b-4fa0-a8d9-29f1e1b8acbc">
UPDATED view

2024-05-22 23:41 UTC, nadavital approved these changes, later dismissed
LGTM

2024-05-23 05:02 UTC, nadavital submitted a review, later dismissed
LGTM

2024-05-24 00:38 UTC, AnikaArora requested changes
Link to dokku deployment?

2024-05-24 00:46 UTC, mczimmermann commented
> Link to dokku deployment?

Just added it to the PR!

2024-05-24 23:27 UTC, pconrad requested changes
See discussion on the #proj-happycows Slack channel here:
* https://ucsb-cs156-s24.slack.com/archives/C073GT1NXUM/p1716580120753429

I think you can repurpose this PR as one that addresses part of issue #30 
and that way it's not at all wasted effort, even though we are going in a different direction.  

In my suggestions, note that I may have missed a few spots, and you will need to rename a file or two.    But you can implement that suggestions simply by clicking them one by one in the PR review (or you can just manually do them in your own editor; your choice.)

2024-05-24 23:27 UTC, pconrad commented on frontend/src/App.js
> +import AdminRemoveUserPage from "main/pages/AdminRemoveUserPage";
```suggestion
import AdminSuspendUserPage from "main/pages/AdminSuspendUserPage";
```

Let's change this to "suspend user", per: #30

2024-05-24 23:27 UTC, pconrad commented on frontend/src/App.js
> +                element={<AdminRemoveUserPage />}
```suggestion
                element={<AdminSuspendUserPage />}
```

2024-05-24 23:27 UTC, pconrad commented on frontend/src/main/components/Users/UsersTable.js
> +    columns.push(ButtonColumn("Edit Commons", "primary", removeCallback, "UsersTable"));
```suggestion
    columns.push(ButtonColumn("Suspend", "primary", suspendCallback, "UsersTable"));
```

2024-05-24 23:27 UTC, pconrad commented on frontend/src/main/components/Users/UsersTable.js
> +    const removeCallback = (row) => {
```suggestion
    const suspendCallback = (row) => { 
```

2024-05-24 23:27 UTC, pconrad commented on frontend/src/main/components/Users/UsersTable.js
> +        navigate(`/admin/remove/user/${row.row.values.id}`)
```suggestion
        navigate(`/admin/suspend/user/${row.row.values.id}`)
```

2024-05-24 23:27 UTC, pconrad commented on frontend/src/main/pages/AdminRemoveUserPage.js
> +const AdminRemoveUserPage = () => {
```suggestion
const AdminSuspendUserPage = () => {
```

2024-05-24 23:27 UTC, pconrad commented on frontend/src/main/pages/AdminRemoveUserPage.js
> +        <h1>Edit User Commons page not yet implemented</h1>
```suggestion
        <h1>Suspend User page not yet implemented</h1>
```

2024-05-24 23:27 UTC, pconrad commented on frontend/src/main/pages/AdminRemoveUserPage.js
> +export default AdminRemoveUserPage;
```suggestion
export default AdminSuspendUserPage;
```

2024-05-24 23:27 UTC, pconrad commented on frontend/src/tests/components/Users/UsersTable.test.js
> +    test("Remove button calls remove callback", async () => {
```suggestion
    test("Suspend button calls suspend callback", async () => {
```

2024-05-24 23:27 UTC, pconrad commented on frontend/src/tests/components/Users/UsersTable.test.js
> +        const editButton = screen.getByTestId(`${testId}-cell-row-0-col-Edit Commons-button`);
```suggestion
        const editButton = screen.getByTestId(`${testId}-cell-row-0-col-Suspend-button`);
```

2024-05-24 23:27 UTC, pconrad commented on frontend/src/tests/components/Users/UsersTable.test.js
> +        await waitFor(() => expect(mockedNavigate).toHaveBeenCalledWith('/admin/remove/user/1'));
```suggestion
        await waitFor(() => expect(mockedNavigate).toHaveBeenCalledWith('/admin/suspend/user/1'));
```

2024-05-24 23:27 UTC, pconrad commented on frontend/src/tests/pages/AdminRemoveUserPage.test.js
> +import AdminRemoveUserPage from "main/pages/AdminRemoveUserPage";
```suggestion
import AdminSuspendUserPage from "main/pages/AdminSuspendUserPage";
```

2024-05-24 23:27 UTC, pconrad commented on frontend/src/tests/pages/AdminRemoveUserPage.test.js
> +describe("AdminRemoveUserPage tests", () => {
```suggestion
describe("AdminSuspendUserPage tests", () => {
```

2024-05-24 23:27 UTC, pconrad commented on frontend/src/tests/pages/AdminRemoveUserPage.test.js
> +                    <AdminRemoveUserPage />
```suggestion
                    <AdminSuspendUserPage />
```

2024-05-24 23:27 UTC, pconrad commented on frontend/src/tests/pages/AdminRemoveUserPage.test.js
> +        expect(screen.getByText("Edit User Commons page not yet implemented")).toBeInTheDocument();
```suggestion
        expect(screen.getByText("Suspend User page not yet implemented")).toBeInTheDocument();
```

2024-05-27 04:32 UTC, mczimmermann commented
Addresses sub-issue F1 within [EPIC:Admin can suspend/restore Users](https://github.com/ucsb-cs156/proj-happycows/issues/124)

2024-05-27 16:42 UTC, pconrad requested changes
Code LGTM!  No problems with the code.

But a few other concerns before we merge this...

It looks like you did follow up on repurposing this to a "suspend user" button.  However, I wonder if you redeployed on dokku?

The dokku deployment still says "Edit Commons".

Also, can you update the PR title and description to match the new focus?
Thanks!

2024-05-28 00:10 UTC, mczimmermann commented
Just updated the dokku deployment and PR info!

2024-05-28 05:54 UTC, nadavital submitted a review, later dismissed
LGTM

2024-05-28 20:10 UTC, nadavital approved these changes
LGTM

2024-05-29 20:42 UTC, pconrad approved these changes
LGTM

2024-05-29 20:43 UTC, merged