zc - announcement page
ucsb-cs156-s24/proj-happycows-s24-4pm-7 pull request #46
Opened 2024-06-05 01:15 UTC by chendashi

## Overview
Announcement page implemented for admin user

## Screenshots (Optional)
![WeChatb175aa03fc7e3b8ff4682b52f2f1ad0b](https://github.com/ucsb-cs156-s24/proj-happycows-s24-4pm-7/assets/17016528/8037092d-65f3-47a1-a8b0-d24d7d77e8be)

## Tests

- [ ] Backend Unit tests (`mvn test`) pass
- [ ] Backend Test coverage (`mvn test jacoco:report`) 100%
- [ ] Backend Mutation tests (`mvn test pitest:mutationCoverage`) 100% 
- [ ] Frontend Unit tests (`npm test`) pass
- [ ] Frontend Test coverage (`npm run coverage`) 100%
- [ ] Frontend Mutation tests (`npx stryker run`) 100% 
- [ ] Frontend Linting (`npx eslint --fix src`) 

## Linked Issues
related to issue #4

2024-06-05 01:18 UTC, james-y-f submitted a review, later dismissed
LGTM!

2024-06-05 01:18 UTC, YixinXue approved these changes, later dismissed
lgtm

2024-06-05 23:13 UTC, pconrad approved these changes
LGTM... will test on dokku

2024-06-06 00:31 UTC, pconrad requested changes
I think there's a bug here.  Try fixing the url to make sure it matches the urls on swagger, deploy to dokku and test, and then let me know.

2024-06-06 00:31 UTC, pconrad commented on frontend/src/main/pages/AdminListAnnouncementsPage.js
> +        { method: "GET", url: `/api/announcements/all`, params: { commonsId } },
Check this against the URLs that are available on swagger.

I think you'll find that this URL doesn't exist.

2024-06-07 01:29 UTC, whuang602 approved these changes
LGTM

2024-06-07 01:32 UTC, merged

2024-06-07 03:04 UTC, pconrad commented
Points reverted because this feature was removed in PR #49